# Generated by Django 4.2.3 on 2023-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.IntegerField()),
                ('p_desc', models.CharField(max_length=300)),
                ('p_category', models.CharField(max_length=20)),
                ('p_owner', models.CharField(max_length=100)),
                ('p_available', models.BooleanField(default=True)),
                ('p_stock', models.IntegerField()),
            ],
        ),
    ]
